# Simplified Cloud Build - Deploy basic services
steps:
  # Deploy a simple frontend
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-frontend'
    - '--image=gcr.io/cloudrun/hello'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'

  # Deploy a simple API
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-api'
    - '--image=gcr.io/cloudrun/hello'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'

  # Deploy a simple worker
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-worker'
    - '--image=gcr.io/cloudrun/hello'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'

timeout: '600s' 