# Cloud Build configuration for frontend-only deployment
steps:
  # Build and deploy the React frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID',
      './frontend'
    ]
    id: 'build-frontend-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID']
    id: 'push-frontend-image'
    waitFor: ['build-frontend-image']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-frontend'
    - '--image=gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=3000'
    - '--memory=512Mi'
    - '--cpu=1'
    - '--max-instances=10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend-image']

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY 