# Cloud Build configuration for Java Spring Boot backend
steps:
  # Build and deploy the React frontend (unchanged)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID',
      './frontend'
    ]
    id: 'build-frontend-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID']
    id: 'push-frontend-image'
    waitFor: ['build-frontend-image']

  # Build and deploy the Java Spring Boot API
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID',
      './backend-java'
    ]
    id: 'build-api-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID']
    id: 'push-api-image'
    waitFor: ['build-api-image']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-frontend'
    - '--image=gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=3000'
    - '--memory=512Mi'
    - '--cpu=1'
    - '--max-instances=10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend-image']

  # Deploy API to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-api'
    - '--image=gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--memory=1Gi'
    - '--cpu=2'
    - '--max-instances=10'
    - '--set-env-vars=SPRING_PROFILES_ACTIVE=production'
    - '--set-env-vars=DATABASE_URL=jdbc:postgresql://localhost:5432/research_platform'
    id: 'deploy-api'
    waitFor: ['push-api-image']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 