# Cloud Build configuration for Staging Environment
# Triggered on pushes to develop branch

steps:
  # Step 1: Install dependencies and run tests
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'
    id: 'install-frontend-deps'

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'test']
    dir: 'frontend'
    id: 'test-frontend'
    waitFor: ['install-frontend-deps']

  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    dir: 'backend'
    id: 'install-backend-deps'

  - name: 'python:3.11'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/']
    dir: 'backend'
    id: 'test-backend'
    waitFor: ['install-backend-deps']

  # Step 2: Build Docker images with staging tags
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:staging-$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:staging-latest',
      './frontend'
    ]
    id: 'build-frontend-image'
    waitFor: ['test-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-api:staging-$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-api:staging-latest',
      './backend/api'
    ]
    id: 'build-api-image'
    waitFor: ['test-backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-worker:staging-$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-worker:staging-latest',
      './backend/worker'
    ]
    id: 'build-worker-image'
    waitFor: ['test-backend']

  # Step 3: Push staging images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:staging-$COMMIT_SHA']
    waitFor: ['build-frontend-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:staging-latest']
    waitFor: ['build-frontend-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-api:staging-$COMMIT_SHA']
    waitFor: ['build-api-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-api:staging-latest']
    waitFor: ['build-api-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-worker:staging-$COMMIT_SHA']
    waitFor: ['build-worker-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-worker:staging-latest']
    waitFor: ['build-worker-image']

  # Step 4: Deploy to staging GKE cluster
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=k8s/staging/
    - --image=gcr.io/$PROJECT_ID/research-platform-frontend:staging-$COMMIT_SHA
    - --image=gcr.io/$PROJECT_ID/research-platform-api:staging-$COMMIT_SHA
    - --image=gcr.io/$PROJECT_ID/research-platform-worker:staging-$COMMIT_SHA
    - --location=us-central1-a
    - --cluster=research-platform-staging-cluster
    - --namespace=staging

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_STANDARD_4'

timeout: '1200s'

substitutions:
  _ENVIRONMENT: 'staging'
  _CLUSTER_NAME: 'research-platform-staging-cluster'
  _CLUSTER_LOCATION: 'us-central1-a'

images:
  - 'gcr.io/$PROJECT_ID/research-platform-frontend:staging-$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/research-platform-frontend:staging-latest'
  - 'gcr.io/$PROJECT_ID/research-platform-api:staging-$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/research-platform-api:staging-latest'
  - 'gcr.io/$PROJECT_ID/research-platform-worker:staging-$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/research-platform-worker:staging-latest' 