# Cloud Build configuration for frontend-only deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform', 'linux/amd64',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:latest',
      './frontend'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'research-platform-frontend',
      '--image', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '512Mi',
      '--cpu', '1'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s' 