# Simplified Cloud Build - Backend Only
steps:
  # Build and deploy the Java Spring Boot API
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID',
      './backend-java'
    ]
    id: 'build-api-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID']
    id: 'push-api-image'
    waitFor: ['build-api-image']

  # Deploy API to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-api'
    - '--image=gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--max-instances=10'
    - '--timeout=300'
    id: 'deploy-api'
    waitFor: ['push-api-image']

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY 