# Cloud Build configuration for Multi-Agent Research Platform (Cloud Run)
# Simplified version for initial deployment

steps:
  # Step 1: Build Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-frontend:latest',
      './frontend'
    ]
    id: 'build-frontend-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-api:latest',
      './backend/api'
    ]
    id: 'build-api-image'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-worker:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/research-platform-worker:latest',
      './backend/worker'
    ]
    id: 'build-worker-image'

  # Step 2: Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID']
    waitFor: ['build-frontend-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-frontend:latest']
    waitFor: ['build-frontend-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID']
    waitFor: ['build-api-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-api:latest']
    waitFor: ['build-api-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-worker:$BUILD_ID']
    waitFor: ['build-worker-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/research-platform-worker:latest']
    waitFor: ['build-worker-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-frontend'
    - '--image=gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=3000'
    - '--memory=512Mi'
    - '--cpu=1'
    - '--max-instances=10'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-api'
    - '--image=gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8000'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--max-instances=20'
    - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'research-platform-worker'
    - '--image=gcr.io/$PROJECT_ID/research-platform-worker:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--no-allow-unauthenticated'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--max-instances=5'
    - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/research-platform-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/research-platform-frontend:latest'
  - 'gcr.io/$PROJECT_ID/research-platform-api:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/research-platform-api:latest'
  - 'gcr.io/$PROJECT_ID/research-platform-worker:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/research-platform-worker:latest' 