spring:
  application:
    name: research-platform
  
# Server Configuration
server:
  port: ${PORT:8080}
    
# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
# Logging Configuration
logging:
  level:
    com.mach33.research: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.context: DEBUG
    org.springframework.beans: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 