name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

env:
  PROJECT_ID: mach33-research-tool-460917
  REGION: us-central1
  REGISTRY_HOSTNAME: gcr.io

jobs:
  # Check if application code exists before running deployment
  check-code:
    name: Check Application Code
    runs-on: ubuntu-latest
    outputs:
      has-frontend: ${{ steps.check.outputs.has-frontend }}
      has-backend: ${{ steps.check.outputs.has-backend }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Check for application code
      id: check
      run: |
        if [ -f "frontend/package.json" ]; then
          echo "has-frontend=true" >> $GITHUB_OUTPUT
        else
          echo "has-frontend=false" >> $GITHUB_OUTPUT
        fi
        
        if [ -f "backend/requirements.txt" ]; then
          echo "has-backend=true" >> $GITHUB_OUTPUT
        else
          echo "has-backend=false" >> $GITHUB_OUTPUT
        fi

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    needs: check-code
    if: needs.check-code.outputs.has-frontend == 'true' && needs.check-code.outputs.has-backend == 'true'
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Configure Workload Identity Federation and generate an access token
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker
      run: |-
        gcloud --quiet auth configure-docker

    # Install frontend dependencies
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    # Run frontend tests
    - name: Run frontend tests
      run: npm test -- --coverage --watchAll=false
      working-directory: ./frontend

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./backend

    # Run backend tests
    - name: Run backend tests
      run: python -m pytest tests/ --cov=./ --cov-report=xml
      working-directory: ./backend

    # Build frontend Docker image
    - name: Build frontend image
      run: |-
        docker build \
          --tag "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-frontend:$GITHUB_SHA" \
          --tag "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-frontend:latest" \
          ./frontend

    # Build API Docker image
    - name: Build API image
      run: |-
        docker build \
          --tag "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-api:$GITHUB_SHA" \
          --tag "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-api:latest" \
          ./backend/api

    # Build worker Docker image
    - name: Build worker image
      run: |-
        docker build \
          --tag "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-worker:$GITHUB_SHA" \
          --tag "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-worker:latest" \
          ./backend/worker

    # Push the Docker images to Google Container Registry
    - name: Publish frontend image
      run: |-
        docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-frontend:$GITHUB_SHA"
        docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-frontend:latest"

    - name: Publish API image
      run: |-
        docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-api:$GITHUB_SHA"
        docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-api:latest"

    - name: Publish worker image
      run: |-
        docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-worker:$GITHUB_SHA"
        docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-worker:latest"

    # Deploy to Cloud Run
    - name: Deploy frontend to Cloud Run
      run: |-
        gcloud run deploy research-platform-frontend \
          --image="$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-frontend:$GITHUB_SHA" \
          --region="$REGION" \
          --platform=managed \
          --allow-unauthenticated \
          --port=3000 \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=10

    - name: Deploy API to Cloud Run
      run: |-
        gcloud run deploy research-platform-api \
          --image="$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-api:$GITHUB_SHA" \
          --region="$REGION" \
          --platform=managed \
          --no-allow-unauthenticated \
          --port=8000 \
          --memory=1Gi \
          --cpu=1 \
          --max-instances=20 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production" \
          --service-account="research-platform-api@$PROJECT_ID.iam.gserviceaccount.com"

    - name: Deploy worker to Cloud Run
      run: |-
        gcloud run deploy research-platform-worker \
          --image="$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-worker:$GITHUB_SHA" \
          --region="$REGION" \
          --platform=managed \
          --no-allow-unauthenticated \
          --memory=1Gi \
          --cpu=1 \
          --max-instances=5 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production" \
          --service-account="research-platform-worker@$PROJECT_ID.iam.gserviceaccount.com"

    # Run database migrations
    - name: Run database migrations
      run: |-
        gcloud run jobs create migration-job-$GITHUB_RUN_ID \
          --image="$REGISTRY_HOSTNAME/$PROJECT_ID/research-platform-api:$GITHUB_SHA" \
          --region="$REGION" \
          --task-count=1 \
          --parallelism=1 \
          --task-timeout=600 \
          --max-retries=3 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production" \
          --service-account="research-platform-api@$PROJECT_ID.iam.gserviceaccount.com" \
          --command="python,manage.py,migrate"
        
        gcloud run jobs execute migration-job-$GITHUB_RUN_ID \
          --region="$REGION" \
          --wait

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: check-code
    if: github.event_name == 'pull_request' && (needs.check-code.outputs.has-frontend == 'true' || needs.check-code.outputs.has-backend == 'true')

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [check-code, setup-build-publish-deploy]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6

    - name: Run performance tests
      run: k6 run tests/performance/load-test.js
      env:
        API_BASE_URL: ${{ secrets.STAGING_API_URL }}

  notify-skip:
    name: Notify Workflow Skipped
    runs-on: ubuntu-latest
    needs: check-code
    if: needs.check-code.outputs.has-frontend == 'false' || needs.check-code.outputs.has-backend == 'false'
    
    steps:
    - name: Notify that deployment was skipped
      run: |
        echo "::notice::Deployment skipped - application code not found"
        echo "Frontend code exists: ${{ needs.check-code.outputs.has-frontend }}"
        echo "Backend code exists: ${{ needs.check-code.outputs.has-backend }}"
        echo "Create frontend/package.json and backend/requirements.txt to enable deployment" 